cask_args appdir: "/Applications"
tap "homebrew/cask-fonts"
brew "adr-tools"
brew "cloc"
brew "bat"
brew "pre-commit"
cask "font-fira-code"
cask "firefox"
brew "git"
brew "git-extras"
brew "gh"
brew "go"
cask "google-chrome"
cask "gpg-suite"
brew "graphviz"
brew "hstr"  # still need to set config by running: hstr --show-configuration >> ~/.zshrc
brew "hugo"
brew "kotlin"
brew "libmagic"
brew "node"
brew "postgresql@11"
brew "pyenv"
brew "readline"
cask "sequel-pro"
cask "sublime-text"
brew "yarn"
brew "tree"
brew "tig"
brew "the_silver_searcher"
cask "the-unarchiver"
cask "vlc"
brew "xz"
brew "zsh"
brew "zsh-syntax-highlighting"  # add to plugin using oh-my-zh
brew "zlib"
